quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:profile.db
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=4
quarkus.datasource.jdbc.acquisition-timeout=30S
quarkus.hibernate-orm.database.generation=update

quarkus.http.port=8080

quarkus.http.cors.enabled=${CORS_ENABLED:true}
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-user-id

profile.media.storage.provider=${PROFILE_MEDIA_STORAGE_PROVIDER:local}
profile.media.local-storage-path=${PROFILE_MEDIA_LOCAL_STORAGE_PATH:/deployments/storage/profile-media}
profile.media.local-public-base-url=${PROFILE_MEDIA_LOCAL_PUBLIC_BASE_URL:http://localhost:9092/profile-service/media/files}
